### PR TITLE
Make homepage tags more responsive

### PR DESCRIPTION
**Pull request by MRX1621**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** and other relevant documents.

## Description

fix: the course-management-tag is responsive, so that it's in every resolution readable

### CODE REVIEW

**Comment by danieljancar** [comment]
Hey @MRX1621 can you please edit your commit message to follow our [commit guidelines](https://github.com/danieljancar/chorizo/blob/develop/.github/CONTRIBUTING.md)? Thanks 🦖

**Review by danieljancar — CHANGES_REQUESTED** [review]
Hey @MRX1621 can you please edit your commit message to follow our [commit guidelines](https://github.com/danieljancar/chorizo/blob/develop/.github/CONTRIBUTING.md)? Thanks 🦖

**Comment by MRX1621** [comment]
commit message is updated

**Comment by danieljancar** [comment]
No still isn't updated also doesn't follow semantic commit messages guidelines, find examples [here](https://github.com/danieljancar/chorizo/commits/develop/).

image

**Review by danieljancar — APPROVED** [review]
Looks good, thanks. 🐵

**Pull request merged**
